import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from "../styles/Home.module.css"
import Button from '@/components/ui/Button/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>TravelEase</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <nav className={styles.header}>
          <img
            src="/undraw_arrow.svg"
            alt="logo"
          />
          <h1>TravelEase</h1>
        </nav>

        <div className={styles.container}>

          <div className={styles.image_container}>
            <img
              src="/undraw_house_searching_re_stk8.svg"
              alt=""
              className={styles.landing_page_img}
            />
          </div>

          <div className={styles.description}>
            <p className={styles.tagline}>Finding Stays Close to Your Itinerary</p>
            <p className={styles.explanation}>
              We help you choose accommodations close to the attractions you plan to visit so that you can optimize your stay for your next trip.
            </p>
            <Button label="Get Started" />

          </div>
        </div>

      </main>
    </>
  )
}
